### PR TITLE
Added orthophoto and skyview layers

### LINKED ISSUE #18: Aditional carto layers
- lidar
- ortophoto
- another openlayers with more details (something like opentopo or similar)

### PR DESCRIPTION
**Pull request by MaticDiba**
For now, I added OrthoPhoto and LidarSkyView layers. Since these two will be eventually available for offline use.

Question: do you have any suggestions on how to load these layers dynamically?  With `v-for=""` on `ol-tile-layer` layer. I would just somehow need to store a reference to that layer element, so I can use it to toggle visibility and set source.

The goal is to have them all defined in the store or even fetch the data from BE. 

Closes #18

### CODE REVIEW

**Comment by jeancaffou** [comment]
@MaticDiba If I understand correctly and the functionality is basically normal and straightforward - you just basically add all the `<ol-tile-layer>`s and then v`-if="state.currentLayer == 'orto'"` them.

I've added you in my work project where I'm basically doing the same thing here:
https://github.com/IK-Servis/mygps-v4/blob/master/src/components/MapView.vue#L35

(You also got the invite for FlySafe mistakenly, where the layer chooser works a little bit differently than in MyGPService-v4)

**Comment by jeancaffou** [comment]
I just remembered that if by dynamically you mean you would add a list of tile URL from the server and not baked in the app, than yes, you would do a `<template v-for="">` and then inside the template you would add `<ol-tile-layer v-if="">` because you can't do a `v-for` and `v-if` on the same tag.

**Comment by MaticDiba** [comment]
@jeancaffou yes, I was asking about dynamically creating elements for these layers. I'm familiar with how `v-for` and `v-if` work. The problem I had was that I need a reference to this layer because I have extra code to load it. I'm not sure there is any way to achieve this the same way as you did with OpenLayers, since for OL you need just a simple xyz layer, but in this case, I need a custom WMTS layer (I think the one provided by `vue3-openlayers` will not work with SLO wmts, at leaset I haven't found a way).

But now I wraped this in a new component. And managed to use it by passing the reference to each layer object through `props`. Although I'm not sure if that's the best practice. I think it's OK for now. Let me know what you think.

**Review by jeancaffou — APPROVED** [review]

**Comment by jeancaffou** [comment]
Still not completely sure what the issue is, but wrapping it a custom component seems like a perfectly reasonable solution.

If the problem is that you need a mixture of different layer types (they're not all `<ol-tile-layer>`) you can still do this in a kind-of switch/case method with
```vue
<template v-for="layer in layers">
   <ol-tile-layer v=if="layer.type == 'tileLayer'" />
   <customWMTSlayer v-else-if="layer.type == 'custom'" />
  <!-- ... -->
</template>

**Comment by MaticDiba** [comment]
The problem was with this: https://github.com/DZRJL/katasterjam-mobile/pull/22/files#diff-2222249dfa9964364b8b4412c0aacb6aad003100c882df0a362860c23c005399R23
Because `v-if` will not work if the condition is initially `false` (this: `layerRef.tileLayer.setVisible(this.layer.active)` will fail). But it's OK now, since I'm passing in the whole layer as a `ref`. And I also managed to subscribe to change (didn't know about `deep: true,`) and there I toggle visibility.

Before I had issues since the layer was not wrapped in a custom component and I was unable to have multiple dynamic refs to a layer. I wanted to do something like this: ` <ol-tile-layer v-fore:'...' ref="dynamicLayerRef">` (but I think there is no solution that would support anything like this). So if passing store item as a ref and then using it in `watch` with `deep: true,` is a good practice. Then I'm OK with this solution.

**Comment by jeancaffou** [comment]
Proposed simplification in https://github.com/MaticDiba/katasterjam-mobile/pull/4

**Pull request merged**
