### PR TITLE
Refactor of location layers to support tracking and navigation

### PR DESCRIPTION
**Pull request by MaticDiba**
I started with a refactoring of the location layer. I want to support users to:
- track his location (and later store/share that track)
- be navigated to a specific location
- location updates should be active all the time

But I'm having issues with the last one: when the user starts using this app, the location should be turned on and show a location marker on the map. This location doesn't have to run in [back/fore]ground (no notification needed). Also if the application is closed, the location should be turned off. But when the user starts navigation/tracking it should use foreground location. Similar to how (for example) Locus maps work. In the future, I would also enable users to turn this off completely. 

For this I tried using `navigator.geolocation.watchPosition` but for some reason, it's not working as it should. I think it's using a location provider from WIFI or LTE (I'm not sure) but not GPS (there is no android icon shown). I'm not sure if this is again a problem with my phone or if there is another way to achieve this. Did you ever experience anything similar? Do you have any idea how to solve this?

### CODE REVIEW

**Comment by jeancaffou** [comment]
There's no way to force GPS location with `navigator.geolocation`, **however**, you can specify `options` with `Geolocation.watchPosition()` or `Geolocation.getCurrentPosition()`, specifically you're interested in using the `enableHighAccuracy: true` option.

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition

In a cordova environment using a plugin, you can specify the [GPS_PROVIDER](https://developer.android.com/reference/android/location/LocationManager#GPS_PROVIDER) option for `LocationManager`.

**Comment by MaticDiba** [comment]
🤦 I was using it (`enableHighAccuracy: true`) [here](https://github.com/DZRJL/katasterjam-mobile/blob/main/src/pages/CaveSearchPage.vue#L168), but forgot to add it in `location-store`

I think that's it ...

**Comment by MaticDiba** [comment]
@jeancaffou this is getting big, so I will stop now :) comments much appreciated.

**Review by jeancaffou — APPROVED** [review]
Vue architecture looks good, don't have much to add other than a general comment about the location listener implementation - seems a little bit convoluted at the moment, supporting multiple listeners. Maybe it could be simplified to do all the logic in the location-store every time anyway (saving track, updating navigation / my location) and just declaratively use them in the `*Layer.vue` files. Since the store properties are reactive, the view should get updated automatically, or if you need extra logic that reacts to changes, you can handle it in the watchers rather than in anonymous functions in `setup()` - this is also an optimization if the location change wouldn't change anything on the view, the watcher wouldn't fire, but the anonymous function would repaint on every call.

**Comment by jeancaffou** [comment]
Just checked, since this was pretty straightforward in Vue2/Vuex, but with Pinia and Vue3, you can set up reactive store properties with `storeToRefs()`. Here is an example: https://stackoverflow.com/a/72530962

**Comment by MaticDiba** [comment]
The reason for those was to have component specific logic there. But probably I didn't think it through enough. It looks like I could move this into watcher, didn't think about it before. Will look into this.

**Comment by MaticDiba** [comment]
@jeancaffou moved a few things around. I think the components are now much cleaner. Didn't even need to use `storeToRef` in most places.

**Comment by jeancaffou** [comment]
Looks good 👍

**Pull request merged**
